# Generated by Django 3.2.6 on 2021-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='poem/images'),
        ),
    ]
