# Generated by Django 3.2.6 on 2021-11-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_poem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='poem/img'),
        ),
    ]
