# Generated by Django 3.2.6 on 2021-11-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_alter_poem_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='poemImg',
            field=models.ImageField(default='', upload_to='poem/poem'),
        ),
    ]
