# Generated by Django 3.2.6 on 2021-11-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0006_poem_poemimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='views',
        ),
    ]
