# Generated by Django 3.2.6 on 2021-12-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0009_poemcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='thumbnail',
        ),
    ]
