# Generated by Django 3.2.6 on 2021-11-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='bxcdycbd cdcuydcd hdyvcuydvcz cdhuobcsdg czlvgsf bxcdycbd cdcuydcd hdyvcuydvcz cdhuobcsdg czlvgsf bxcdycbd cdcuydcd hdyvcuydvcz cdhuobcsdg czlvgsf bxcdycbd cdcuydcd hdyvcuydvcz cdhuobcsdg czlvgsf bxcdycbd cdcuydcd hdyvcuydvcz cdhuobcsdg czlvgsf bxcdycbd cdcuydcd hdyvcuydvcz cdhuobcsdg czlvgsf'),
            preserve_default=False,
        ),
    ]
